export const findNote = 'find-note'
export const createNote = 'create-note'
export const deleteNote = 'delete-note'
export const updateNote = 'update-note'
export const findAllNotesList = 'find-all-notes-list'